include include.mk

include ../make_module/makefile_templates/ros_msg_project_makefile_template.mk

.PHONY: test
test:
	echo "${adore_if_ros_scheduling_msg_tag}"
	echo "$(call get_docker_submodule_tags,$(submodules))"
