
SHELL:=/bin/bash

.DEFAULT_GOAL := all

ROOT_DIR:=$(shell dirname "$(realpath $(firstword $(MAKEFILE_LIST)))")

include adore_if_ros_scheduling.mk

MAKEFLAGS += --no-print-directory


.EXPORT_ALL_VARIABLES:
DOCKER_BUILDKIT?=1
DOCKER_CONFIG?=

.PHONY: all
all: build

.PHONY: set_env 
set_env: 
	$(eval project := ${adore_if_ros_scheduling_project}) 
	$(eval tag := ${adore_if_ros_scheduling_tag})

.PHONY: build 
build: root_check docker_group_check set_env clean build_adore_if_ros_scheduling_msg build_libadore_scheduling ## Build adore_if_ros_scheduling 
	docker build --network host \
                 --tag ${project}:${tag} \
                 --build-arg project=${project} \
                 --build-arg libadore_scheduling_tag=${lib_adore_scheduling_tag} \
                 --build-arg adore_if_ros_scheduling_msg_tag=${adore_if_ros_scheduling_msg_tag} .
	docker cp $$(docker create --rm ${project}:${tag}):/tmp/${project}/${project}/build "${ROOT_DIR}/${project}"

.PHONY: clean_submodules
clean_submodules: set_env clean_libadore_scheduling clean_adore_if_ros_scheduling_msg

.PHONY: clean
clean: set_env clean_submodules ## Clean adore_if_ros_scheduling build artifacts
	rm -rf "${ROOT_DIR}/${project}/build"
	docker rm $$(docker ps -a -q --filter "ancestor=${project}:${tag}") --force 2> /dev/null || true
	docker rmi $$(docker images -q ${project}:${tag}) --force 2> /dev/null || true

